
name: auto_commit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5  
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build bundle
        run: npm run build
    
  commit:
   needs: build
   runs-on: ubuntu-latest
   steps:
      - name: Clone Sakurairo
        uses: actions/checkout@v2
        with:
            repository: mirai-mamori/Sakurairo
            path: ./theme
            ref: preview
      - name: Copy and paste
        run: cp $GITHUB_WORKSPACE/dist/sakura-app.js $GITHUB_WORKSPACE/theme/js/sakura-app.js
             cp $GITHUB_WORKSPACE/dist/sakura-app.js.map $GITHUB_WORKSPACE/theme/js/sakura-app.js.map
             cp $GITHUB_WORKSPACE/dist/sakura-app.js.LICENSE.txt $GITHUB_WORKSPACE/theme/js/sakura-app.js.LICENSE.txt
      - name: Commit
        run: cd $GITHUB_WORKSPACE/theme
             git push
   
   
